# Comparative Study of Gradient Boosting, XGBoost, and Deep Learning Models for Parkinson’s Disease Detection from Voice Features

## Overview

This notebook presents a comparison between three different modeling approaches:

- Gradient Boosting (classical machine learning)
- XGBoost (advanced boosting)
- FastAI Tabular (deep learning)

The goal is to evaluate their performance on Parkinson’s disease detection using voice-based biomedical features.

## Experimental Setup

To ensure fair comparison, all models were evaluated under the same conditions:

- Dataset: Parkinson’s voice dataset (228 samples, 19 features)
- Feature set: identical across all models
- Train-test split: stratified 80/20
- Evaluation metrics:
  - Accuracy
  - Precision
  - Recall
  - F1-score
  - ROC-AUC
  - MCC

No cross-validation was applied; results are based on a single validation split.

In [1]:
import pandas as pd

In [2]:
fastai_results = {
    "model": "FastAI Tabular (DL)",
    "accuracy": 0.9565,
    "precision": 0.9737,
    "recall": 0.9737,
    "f1_score": 0.9737,
    "roc_auc": 0.9901,
    "mcc": 0.8487,
    "notes": "Weighted + threshold tuned (0.10)"
}

In [3]:
gb_results = {
    "model": "Gradient Boosting (ML)",
    "accuracy": 0.9565,
    "precision": 0.9737,
    "recall": 0.9737,
    "f1_score": 0.9737,
    "roc_auc": 0.9868,
    "mcc": 0.8487,
    "notes": "Loaded from saved model"
}

In [4]:
xgb_results = {
    "model": "XGBoost (ML)",
    "accuracy": 0.9348,
    "precision": 0.9268,
    "recall": 1.0000,
    "f1_score": 0.9620,
    "roc_auc": 0.9638,
    "mcc": 0.7611,
    "notes": "Perfect recall; screening-oriented"
}

In [5]:
comparison_df = pd.DataFrame([gb_results, xgb_results, fastai_results])
comparison_df.round(4)

,model,accuracy,precision,recall,f1_score,roc_auc,mcc,notes
0,Gradient Boosting (ML),0.9565,0.9737,0.9737,0.9737,0.9868,0.8487,Loaded from saved model
1,XGBoost (ML),0.9348,0.9268,1.0000,0.9620,0.9638,0.7611,Perfect recall; screening-oriented
2,FastAI Tabular (DL),0.9565,0.9737,0.9737,0.9737,0.9901,0.8487,Weighted + threshold tuned (0.10)


## Model Roles

Each model represents a different learning approach:

- **Gradient Boosting:** classical ensemble-based machine learning
- **XGBoost:** optimized gradient boosting with stronger recall behavior
- **FastAI Tabular:** deep learning for structured tabular biomedical data

This comparison helps evaluate whether classical ML or deep learning is more effective for Parkinson’s disease detection from handcrafted voice features.

## Comparison Summary

### Key Findings

- **FastAI Tabular** achieved the highest ROC-AUC (**0.9901**), indicating the strongest overall class separation.
- **Gradient Boosting** delivered the most balanced prediction behavior, with strong metrics across all evaluation criteria.
- **XGBoost** achieved perfect recall (**1.0000**), meaning no Parkinson cases were missed on the validation split.

### Trade-offs

- **FastAI Tabular:** best overall ranking ability
- **Gradient Boosting:** most stable and balanced classical model
- **XGBoost:** most suitable for recall-critical screening scenarios

### Interpretation

These results suggest that:
- classical machine learning remains highly competitive on structured biomedical data
- deep learning can offer slight improvement in ranking performance
- model selection should depend on application priorities, not accuracy alone

In [6]:
comparison_df.to_csv("../models/final_model_comparison.csv", index=False)
print("Saved final comparison to ../models/final_model_comparison.csv")

Saved final comparison to ../models/final_model_comparison.csv


## Practical Implications

- For **clinical screening systems**, XGBoost is preferable due to perfect recall.
- For **balanced diagnostic tools**, Gradient Boosting provides stable predictions.
- For **general-purpose predictive systems**, FastAI Tabular offers the best overall performance.

This highlights that model selection should align with application requirements.

## Final Conclusion

All three models demonstrated strong performance for Parkinson’s disease detection from voice-based biomedical features.

- **FastAI Tabular** is the best overall model based on ROC-AUC and generalization strength.
- **Gradient Boosting** offers highly balanced and reliable classification performance.
- **XGBoost** is most attractive for medical screening scenarios where maximizing recall is more important than minimizing false positives.

Overall, this study shows that both machine learning and deep learning models can be highly effective when applied to well-engineered biomedical voice features.

Note: Note: Results are based on a single stratified validation split. Future work may include cross-validation for more robust performance estimation.